### ISSUE TITLE
Guard account able to receive future fund but unable to withdraw

### ISSUE THREAD

**Issue by elonkusk** [uniworld-io/unichain-core#26]
**Describe the bug**
Guard account able to receive future send but unable to withdraw
**To Reproduce**
1. Go to testnet
2. From genesis account UinLtqgPm9waBdUSVAAzRR6pfBzfQNC4c2  send future fund to the guard  account  Uk28n4A28nfXhgYWnRr6mXDbTbAeCkEtJ7
2. Wait for deal to expired 
`"future_supply": {
		"total_deal": 2,
		"lower_time": 1640044800000,
		"upper_time": 1640131200000,
		"total_balance": 200000000,
		"lower_tick": "44efbfbd4b36efbfbdefbfbd2aefbfbdefbfbd596aefbfbdefbfbdefbfbdefbfbd29efbfbdefbfbdefbfbd455f31363430303434383030303030",
		"upper_tick": "44efbfbd4b36efbfbdefbfbd2aefbfbdefbfbd596aefbfbdefbfbdefbfbdefbfbd29efbfbdefbfbdefbfbd455f31363430313331323030303030"
	}`
3. Withdraw deals
4. See error:
`13:49:04.816 ERROR [pool-48-thread-1] [actuator](WithdrawFutureActuator.java:77) Account[44f1b94b36daea2ad0ca596af689d0fd29bccfd845] is a guard representative and is not allowed to withdraw Balance
java.lang.IllegalArgumentException: Account[44f1b94b36daea2ad0ca596af689d0fd29bccfd845] is a guard representative and is not allowed to withdraw Balance
	at org.springframework.util.Assert.isTrue(Assert.java:68)
	at org.unichain.core.actuator.WithdrawFutureActuator.validate(WithdrawFutureActuator.java:72)
	at org.unichain.core.Wallet.createTransactionCapsule(Wallet.java:330)
	at org.unichain.core.services.RpcApiService.createTransactionCapsule(RpcApiService.java:173)
	at org.unichain.core.services.RpcApiService.access$700(RpcApiService.java:59)
	at org.unichain.core.services.RpcApiService$WalletApi.withdrawFutureTransaction(RpcApiService.java:1315)
	at org.unichain.api.WalletGrpc$MethodHandlers.invoke(WalletGrpc.java:8638)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:707)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Expected behavior**
Dont allowed to send future fund to guard account.

**Comment by realelonmusk102** [comment]
@elonkusk we should
- allow  send future to guard guard representative (hard-coded witness)
- allow  withdraw future by guard guard representative (hard-coded witness)

**Comment by realelonmusk102** [comment]
@elonkusk resolved:

- On testnet, upgrade to block ver 3
`18:19:09.118 INFO  [UnichainJClientWorker-1] [DB](Manager.java:1116) saved block: BlockCapsule 
[ blockVersion=3
hash=000000000000d9906fa5e24bbd604a2f2628bcbb17f804906f77a6515c35c73b
number=55696
parentId=000000000000d98f4dcdd3ffed22bfaf220b4bab83137ff17303eccb0262876c
witness address=44f1b94b36daea2ad0ca596af689d0fd29bccfd845
generated by myself=false
generate time=2021-12-22 18:19:09.0
txs are empty
]
`
- withdraw future fund on guard account Uk28n4A28nfXhgYWnRr6mXDbTbAeCkEtJ7
`wallet> GetAccount Uk28n4A28nfXhgYWnRr6mXDbTbAeCkEtJ7
GetAccount with hashed address --> 44f1b94b36daea2ad0ca596af689d0fd29bccfd845, plain text --> Uk28n4A28nfXhgYWnRr6mXDbTbAeCkEtJ7
{
	"type": "AssetIssue",
	"address": "Uk28n4A28nfXhgYWnRr6mXDbTbAeCkEtJ7",
	"balance": 999999499,
	"latest_opration_time": 1640194884000,
	"allowance": 22282544265,
	"is_witness": true,
	"latest_consume_free_time": 1640026950000,
	"account_resource": {
		
	},
	"future_supply": {
		"total_deal": 2,
		"lower_time": 1640044800000,
		"upper_time": 1640131200000,
		"total_balance": 200000000,
		"lower_tick": "44efbfbd4b36efbfbdefbfbd2aefbfbdefbfbd596aefbfbdefbfbdefbfbdefbfbd29efbfbdefbfbdefbfbd455f31363430303434383030303030",
		"upper_tick": "44efbfbd4b36efbfbdefbfbd2aefbfbdefbfbd596aefbfbdefbfbdefbfbdefbfbd29efbfbdefbfbdefbfbd455f31363430313331323030303030"
	},
	"token": [
		{
			"key": "SSI",
			"value": 3000000
		}
	],
	"token_future": [
		{
			"key": "SSI",
			"value": {
				"token_name": "SSI",
				"total_deal": 1,
				"lower_bound_time": 1640217600000,
				"upper_bound_time": 1640217600000,
				"total_value": 1000000,
				"lower_tick": "44efbfbd4b36efbfbdefbfbd2aefbfbdefbfbd596aefbfbdefbfbdefbfbdefbfbd29efbfbdefbfbdefbfbd455f5353495f31363430323137363030303030",
				"upper_tick": "44efbfbd4b36efbfbdefbfbd2aefbfbdefbfbd596aefbfbdefbfbdefbfbdefbfbd29efbfbdefbfbdefbfbd455f5353495f31363430323137363030303030"
			}
		}
	]
}
`
- successfully withdraw funds:
`wallet> WithdrawFuture 
{
	"raw_data":{
		"contract":[
			{
				"parameter":{
					"value":{
						"owner_address":"44f1b94b36daea2ad0ca596af689d0fd29bccfd845"
					},
					"type_url":"type.googleapis.com/protocol.FutureWithdrawContract"
				},
				"type":"FutureWithdrawContract"
			}
		],
		"ref_block_bytes":"d9ba",
		"ref_block_hash":"d04fe6b4702105cd",
		"expiration":1640197341000,
		"timestamp":1640197283309
	},
	"raw_data_hex":"0a02d9ba2208d04fe6b4702105cd40c8fe849bde2f5a520834124e0a33747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e4675747572655769746864726177436f6e747261637412170a1544f1b94b36daea2ad0ca596af689d0fd29bccfd84570edbb819bde2f"
}
`
`wallet> GetAccount Uk28n4A28nfXhgYWnRr6mXDbTbAeCkEtJ7
GetAccount with hashed address --> 44f1b94b36daea2ad0ca596af689d0fd29bccfd845, plain text --> Uk28n4A28nfXhgYWnRr6mXDbTbAeCkEtJ7
{
	"type": "AssetIssue",
	"address": "Uk28n4A28nfXhgYWnRr6mXDbTbAeCkEtJ7",
	"balance": 1199999254,
	"latest_opration_time": 1640197290000,
	"allowance": 22316944179,
	"is_witness": true,
	"latest_consume_free_time": 1640026950000,
	"account_resource": {
		
	},
	"token": [
		{
			"key": "SSI",
			"value": 3000000
		}
	],
	"token_future": [
		{
			"key": "SSI",
			"value": {
				"token_name": "SSI",
				"total_deal": 1,
				"lower_bound_time": 1640217600000,
				"upper_bound_time": 1640217600000,
				"total_value": 1000000,
				"lower_tick": "44efbfbd4b36efbfbdefbfbd2aefbfbdefbfbd596aefbfbdefbfbdefbfbdefbfbd29efbfbdefbfbdefbfbd455f5353495f31363430323137363030303030",
				"upper_tick": "44efbfbd4b36efbfbdefbfbd2aefbfbdefbfbd596aefbfbdefbfbdefbfbdefbfbd29efbfbdefbfbdefbfbd455f5353495f31363430323137363030303030"
			}
		}
	]
}
`
